import type { PhotoItem, VideoItem } from '@/types';

/**
 * All Bunz media items — photos and videos from /public/media/images/bunz/.
 * Accessed via the secret BunzPanel, triggered by the Bunz link in Our Story.
 * Width/height on photos are placeholder values; the grid CSS (aspect-[4/5])
 * and focused modal CSS (max-h-[70dvh] object-contain) handle layout.
 */
export const bunzItems: ReadonlyArray<PhotoItem | VideoItem> = [
  {
    id: 'bunz-5fd472ec-076b-4c58-a2ea-7bc11fb44a7c-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/5FD472EC-076B-4C58-A2EA-7BC11FB44A7C.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: 5FD472EC-076B-4C58-A2EA-7BC11FB44A7C.webp',
  },
  {
    id: 'bunz-be95fc03-a4d1-4c02-8f9f-8581c1ca5528-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/BE95FC03-A4D1-4C02-8F9F-8581C1CA5528.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: BE95FC03-A4D1-4C02-8F9F-8581C1CA5528.webp',
  },
  {
    id: 'bunz-enlight402-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/Enlight402.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: Enlight402.webp',
  },
  {
    id: 'bunz-enlight667-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/Enlight667.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: Enlight667.webp',
  },
  {
    id: 'bunz-enlight9-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/Enlight9.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: Enlight9.webp',
  },
  {
    id: 'bunz-heif-image-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/HEIF Image.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: HEIF Image.webp',
  },
  {
    id: 'bunz-img-0004-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_0004.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0004.mp4',
  },
  {
    id: 'bunz-img-0005-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0005.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0005.webp',
  },
  {
    id: 'bunz-img-0008-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0008.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0008.webp',
  },
  {
    id: 'bunz-img-0010-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0010.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0010.webp',
  },
  {
    id: 'bunz-img-0015-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0015.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0015.webp',
  },
  {
    id: 'bunz-img-0100-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0100.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0100.webp',
  },
  {
    id: 'bunz-img-0102-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0102.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0102.webp',
  },
  {
    id: 'bunz-img-0134-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_0134.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0134.mp4',
  },
  {
    id: 'bunz-img-0158-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0158.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0158.webp',
  },
  {
    id: 'bunz-img-0169-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0169.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0169.webp',
  },
  {
    id: 'bunz-img-0179-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0179.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0179.webp',
  },
  {
    id: 'bunz-img-0341-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0341.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0341.webp',
  },
  {
    id: 'bunz-img-0577-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0577.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0577.webp',
  },
  {
    id: 'bunz-img-0600-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0600.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0600.webp',
  },
  {
    id: 'bunz-img-0607-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0607.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0607.webp',
  },
  {
    id: 'bunz-img-0623-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0623.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0623.webp',
  },
  {
    id: 'bunz-img-0660-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0660.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0660.webp',
  },
  {
    id: 'bunz-img-0729-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0729.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0729.webp',
  },
  {
    id: 'bunz-img-0845-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0845.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0845.webp',
  },
  {
    id: 'bunz-img-0923-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0923.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0923.webp',
  },
  {
    id: 'bunz-img-0935-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0935.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0935.webp',
  },
  {
    id: 'bunz-img-0982-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0982.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0982.webp',
  },
  {
    id: 'bunz-img-0993-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_0993.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_0993.webp',
  },
  {
    id: 'bunz-img-1012-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1012.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1012.webp',
  },
  {
    id: 'bunz-img-1079-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1079.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1079.webp',
  },
  {
    id: 'bunz-img-1099-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1099.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1099.webp',
  },
  {
    id: 'bunz-img-1117-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_1117.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1117.mp4',
  },
  {
    id: 'bunz-img-1145-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1145.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1145.webp',
  },
  {
    id: 'bunz-img-1148-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1148.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1148.webp',
  },
  {
    id: 'bunz-img-1152-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1152.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1152.webp',
  },
  {
    id: 'bunz-img-1188-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1188.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1188.webp',
  },
  {
    id: 'bunz-img-1214-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1214.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1214.webp',
  },
  {
    id: 'bunz-img-1218-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1218.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1218.webp',
  },
  {
    id: 'bunz-img-1222-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1222.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1222.webp',
  },
  {
    id: 'bunz-img-1243-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1243.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1243.webp',
  },
  {
    id: 'bunz-img-1264-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1264.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1264.webp',
  },
  {
    id: 'bunz-img-1276-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1276.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1276.webp',
  },
  {
    id: 'bunz-img-1279-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1279.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1279.webp',
  },
  {
    id: 'bunz-img-1301-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1301.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1301.webp',
  },
  {
    id: 'bunz-img-1309-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1309.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1309.webp',
  },
  {
    id: 'bunz-img-1419-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1419.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1419.webp',
  },
  {
    id: 'bunz-img-1436-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1436.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1436.webp',
  },
  {
    id: 'bunz-img-1437-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1437.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1437.webp',
  },
  {
    id: 'bunz-img-1468-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1468.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1468.webp',
  },
  {
    id: 'bunz-img-1479-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1479.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1479.webp',
  },
  {
    id: 'bunz-img-1486-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1486.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1486.webp',
  },
  {
    id: 'bunz-img-1499-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1499.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1499.webp',
  },
  {
    id: 'bunz-img-1501-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1501.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1501.webp',
  },
  {
    id: 'bunz-img-1509-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1509.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1509.webp',
  },
  {
    id: 'bunz-img-1514-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1514.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1514.webp',
  },
  {
    id: 'bunz-img-1515-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1515.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1515.webp',
  },
  {
    id: 'bunz-img-1523-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1523.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1523.webp',
  },
  {
    id: 'bunz-img-1525-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1525.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1525.webp',
  },
  {
    id: 'bunz-img-1529-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_1529.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1529.mp4',
  },
  {
    id: 'bunz-img-1531-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1531.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1531.webp',
  },
  {
    id: 'bunz-img-1534-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1534.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1534.webp',
  },
  {
    id: 'bunz-img-1541-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1541.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1541.webp',
  },
  {
    id: 'bunz-img-1564-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1564.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1564.webp',
  },
  {
    id: 'bunz-img-1573-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1573.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1573.webp',
  },
  {
    id: 'bunz-img-1611-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1611.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1611.webp',
  },
  {
    id: 'bunz-img-1653-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1653.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1653.webp',
  },
  {
    id: 'bunz-img-1655-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1655.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1655.webp',
  },
  {
    id: 'bunz-img-1660-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_1660.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1660.mp4',
  },
  {
    id: 'bunz-img-1668-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1668.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1668.webp',
  },
  {
    id: 'bunz-img-1671-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_1671.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1671.mp4',
  },
  {
    id: 'bunz-img-1671-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1671.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1671.webp',
  },
  {
    id: 'bunz-img-1688-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1688.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1688.webp',
  },
  {
    id: 'bunz-img-1701-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1701.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1701.webp',
  },
  {
    id: 'bunz-img-1709-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1709.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1709.webp',
  },
  {
    id: 'bunz-img-1754-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1754.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1754.webp',
  },
  {
    id: 'bunz-img-1760-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1760.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1760.webp',
  },
  {
    id: 'bunz-img-1768-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1768.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1768.webp',
  },
  {
    id: 'bunz-img-1779-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1779.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1779.webp',
  },
  {
    id: 'bunz-img-1798-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1798.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1798.webp',
  },
  {
    id: 'bunz-img-1816-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1816.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1816.webp',
  },
  {
    id: 'bunz-img-1818-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1818.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1818.webp',
  },
  {
    id: 'bunz-img-1838-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1838.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1838.webp',
  },
  {
    id: 'bunz-img-1842-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1842.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1842.webp',
  },
  {
    id: 'bunz-img-1866-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1866.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1866.webp',
  },
  {
    id: 'bunz-img-1872-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1872.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1872.webp',
  },
  {
    id: 'bunz-img-1881-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1881.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1881.webp',
  },
  {
    id: 'bunz-img-1917-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1917.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1917.webp',
  },
  {
    id: 'bunz-img-1919-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1919.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1919.webp',
  },
  {
    id: 'bunz-img-1962-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_1962.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_1962.webp',
  },
  {
    id: 'bunz-img-2014-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2014.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2014.webp',
  },
  {
    id: 'bunz-img-2045-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2045.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2045.webp',
  },
  {
    id: 'bunz-img-2070-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_2070.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2070.mp4',
  },
  {
    id: 'bunz-img-2072-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2072.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2072.webp',
  },
  {
    id: 'bunz-img-2074-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2074.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2074.webp',
  },
  {
    id: 'bunz-img-2081-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2081.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2081.webp',
  },
  {
    id: 'bunz-img-2089-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2089.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2089.webp',
  },
  {
    id: 'bunz-img-2110-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2110.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2110.webp',
  },
  {
    id: 'bunz-img-2111-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2111.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2111.webp',
  },
  {
    id: 'bunz-img-2133-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2133.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2133.webp',
  },
  {
    id: 'bunz-img-2155-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2155.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2155.webp',
  },
  {
    id: 'bunz-img-2157-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2157.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2157.webp',
  },
  {
    id: 'bunz-img-2158-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2158.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2158.webp',
  },
  {
    id: 'bunz-img-2160-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2160.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2160.webp',
  },
  {
    id: 'bunz-img-2214-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2214.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2214.webp',
  },
  {
    id: 'bunz-img-2234-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2234.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2234.webp',
  },
  {
    id: 'bunz-img-2236-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2236.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2236.webp',
  },
  {
    id: 'bunz-img-2239-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2239.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2239.webp',
  },
  {
    id: 'bunz-img-2263-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2263.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2263.webp',
  },
  {
    id: 'bunz-img-2285-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2285.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2285.webp',
  },
  {
    id: 'bunz-img-2288-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_2288.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2288.mp4',
  },
  {
    id: 'bunz-img-2310-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2310.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2310.webp',
  },
  {
    id: 'bunz-img-2329-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2329.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2329.webp',
  },
  {
    id: 'bunz-img-2331-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2331.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2331.webp',
  },
  {
    id: 'bunz-img-2335-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2335.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2335.webp',
  },
  {
    id: 'bunz-img-2378-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2378.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2378.webp',
  },
  {
    id: 'bunz-img-2517-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2517.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2517.webp',
  },
  {
    id: 'bunz-img-2544-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2544.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2544.webp',
  },
  {
    id: 'bunz-img-2556-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2556.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2556.webp',
  },
  {
    id: 'bunz-img-2578-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2578.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2578.webp',
  },
  {
    id: 'bunz-img-2608-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2608.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2608.webp',
  },
  {
    id: 'bunz-img-2611-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2611.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2611.webp',
  },
  {
    id: 'bunz-img-2620-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2620.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2620.webp',
  },
  {
    id: 'bunz-img-2628-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2628.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2628.webp',
  },
  {
    id: 'bunz-img-2686-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2686.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2686.webp',
  },
  {
    id: 'bunz-img-2718-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2718.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2718.webp',
  },
  {
    id: 'bunz-img-2732-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_2732.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2732.mp4',
  },
  {
    id: 'bunz-img-2736-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2736.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2736.webp',
  },
  {
    id: 'bunz-img-2766-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2766.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2766.webp',
  },
  {
    id: 'bunz-img-2776-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2776.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2776.webp',
  },
  {
    id: 'bunz-img-2816-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2816.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2816.webp',
  },
  {
    id: 'bunz-img-2838-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2838.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2838.webp',
  },
  {
    id: 'bunz-img-2839-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2839.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2839.webp',
  },
  {
    id: 'bunz-img-2847-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2847.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2847.webp',
  },
  {
    id: 'bunz-img-2862-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2862.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2862.webp',
  },
  {
    id: 'bunz-img-2893-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2893.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2893.webp',
  },
  {
    id: 'bunz-img-2897-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2897.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2897.webp',
  },
  {
    id: 'bunz-img-2918-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_2918.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2918.mp4',
  },
  {
    id: 'bunz-img-2940-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2940.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2940.webp',
  },
  {
    id: 'bunz-img-2945-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2945.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2945.webp',
  },
  {
    id: 'bunz-img-2971-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2971.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2971.webp',
  },
  {
    id: 'bunz-img-2996-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2996.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2996.webp',
  },
  {
    id: 'bunz-img-2999-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_2999.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_2999.webp',
  },
  {
    id: 'bunz-img-3015-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3015.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3015.webp',
  },
  {
    id: 'bunz-img-3019-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3019.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3019.webp',
  },
  {
    id: 'bunz-img-3049-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3049.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3049.webp',
  },
  {
    id: 'bunz-img-3067-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3067.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3067.webp',
  },
  {
    id: 'bunz-img-3081-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3081.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3081.webp',
  },
  {
    id: 'bunz-img-3094-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3094.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3094.webp',
  },
  {
    id: 'bunz-img-3127-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3127.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3127.webp',
  },
  {
    id: 'bunz-img-3135-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3135.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3135.webp',
  },
  {
    id: 'bunz-img-3147-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3147.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3147.webp',
  },
  {
    id: 'bunz-img-3151-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3151.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3151.webp',
  },
  {
    id: 'bunz-img-3152-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3152.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3152.webp',
  },
  {
    id: 'bunz-img-3158-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3158.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3158.webp',
  },
  {
    id: 'bunz-img-3180-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3180.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3180.webp',
  },
  {
    id: 'bunz-img-3253-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3253.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3253.webp',
  },
  {
    id: 'bunz-img-3294-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3294.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3294.webp',
  },
  {
    id: 'bunz-img-3302-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3302.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3302.webp',
  },
  {
    id: 'bunz-img-3312-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3312.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3312.webp',
  },
  {
    id: 'bunz-img-3314-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3314.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3314.webp',
  },
  {
    id: 'bunz-img-3359-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3359.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3359.webp',
  },
  {
    id: 'bunz-img-3383-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3383.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3383.webp',
  },
  {
    id: 'bunz-img-3393-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3393.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3393.webp',
  },
  {
    id: 'bunz-img-3401-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3401.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3401.webp',
  },
  {
    id: 'bunz-img-3432-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3432.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3432.webp',
  },
  {
    id: 'bunz-img-3443-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3443.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3443.webp',
  },
  {
    id: 'bunz-img-3465-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3465.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3465.webp',
  },
  {
    id: 'bunz-img-3474-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3474.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3474.webp',
  },
  {
    id: 'bunz-img-3481-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3481.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3481.webp',
  },
  {
    id: 'bunz-img-3534-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3534.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3534.webp',
  },
  {
    id: 'bunz-img-3543-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3543.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3543.webp',
  },
  {
    id: 'bunz-img-3579-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3579.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3579.webp',
  },
  {
    id: 'bunz-img-3591-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3591.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3591.webp',
  },
  {
    id: 'bunz-img-3647-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3647.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3647.webp',
  },
  {
    id: 'bunz-img-3653-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3653.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3653.webp',
  },
  {
    id: 'bunz-img-3707-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3707.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3707.webp',
  },
  {
    id: 'bunz-img-3743-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3743.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3743.webp',
  },
  {
    id: 'bunz-img-3784-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3784.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3784.webp',
  },
  {
    id: 'bunz-img-3794-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3794.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3794.webp',
  },
  {
    id: 'bunz-img-3807-2-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3807 2.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3807 2.webp',
  },
  {
    id: 'bunz-img-3807-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3807.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3807.webp',
  },
  {
    id: 'bunz-img-3833-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3833.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3833.webp',
  },
  {
    id: 'bunz-img-3837-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3837.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3837.webp',
  },
  {
    id: 'bunz-img-3843-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3843.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3843.webp',
  },
  {
    id: 'bunz-img-3868-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3868.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3868.webp',
  },
  {
    id: 'bunz-img-3877-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3877.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3877.webp',
  },
  {
    id: 'bunz-img-3879-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3879.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3879.webp',
  },
  {
    id: 'bunz-img-3884-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_3884.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3884.mp4',
  },
  {
    id: 'bunz-img-3885-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3885.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3885.webp',
  },
  {
    id: 'bunz-img-3920-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3920.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3920.webp',
  },
  {
    id: 'bunz-img-3953-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3953.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3953.webp',
  },
  {
    id: 'bunz-img-3957-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3957.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3957.webp',
  },
  {
    id: 'bunz-img-3960-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3960.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3960.webp',
  },
  {
    id: 'bunz-img-3961-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_3961.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_3961.webp',
  },
  {
    id: 'bunz-img-4030-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4030.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4030.webp',
  },
  {
    id: 'bunz-img-4085-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4085.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4085.webp',
  },
  {
    id: 'bunz-img-4093-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4093.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4093.webp',
  },
  {
    id: 'bunz-img-4099-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4099.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4099.webp',
  },
  {
    id: 'bunz-img-4132-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4132.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4132.webp',
  },
  {
    id: 'bunz-img-4144-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4144.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4144.webp',
  },
  {
    id: 'bunz-img-4151-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4151.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4151.webp',
  },
  {
    id: 'bunz-img-4204-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4204.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4204.webp',
  },
  {
    id: 'bunz-img-4212-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4212.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4212.webp',
  },
  {
    id: 'bunz-img-4313-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4313.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4313.webp',
  },
  {
    id: 'bunz-img-4332-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4332.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4332.webp',
  },
  {
    id: 'bunz-img-4341-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4341.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4341.webp',
  },
  {
    id: 'bunz-img-4450-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4450.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4450.webp',
  },
  {
    id: 'bunz-img-4475-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4475.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4475.webp',
  },
  {
    id: 'bunz-img-4531-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4531.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4531.webp',
  },
  {
    id: 'bunz-img-4593-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_4593.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4593.mp4',
  },
  {
    id: 'bunz-img-4596-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4596.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4596.webp',
  },
  {
    id: 'bunz-img-4604-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4604.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4604.webp',
  },
  {
    id: 'bunz-img-4696-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4696.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4696.webp',
  },
  {
    id: 'bunz-img-4717-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4717.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4717.webp',
  },
  {
    id: 'bunz-img-4718-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4718.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4718.webp',
  },
  {
    id: 'bunz-img-4744-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4744.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4744.webp',
  },
  {
    id: 'bunz-img-4759-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4759.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4759.webp',
  },
  {
    id: 'bunz-img-4766-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4766.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4766.webp',
  },
  {
    id: 'bunz-img-4777-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4777.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4777.webp',
  },
  {
    id: 'bunz-img-4789-2-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4789 2.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4789 2.webp',
  },
  {
    id: 'bunz-img-4789-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4789.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4789.webp',
  },
  {
    id: 'bunz-img-4791-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4791.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4791.webp',
  },
  {
    id: 'bunz-img-4822-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4822.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4822.webp',
  },
  {
    id: 'bunz-img-4886-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4886.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4886.webp',
  },
  {
    id: 'bunz-img-4977-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4977.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4977.webp',
  },
  {
    id: 'bunz-img-4986-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_4986.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_4986.webp',
  },
  {
    id: 'bunz-img-5028-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5028.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5028.webp',
  },
  {
    id: 'bunz-img-5122-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5122.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5122.webp',
  },
  {
    id: 'bunz-img-5138-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5138.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5138.webp',
  },
  {
    id: 'bunz-img-5177-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5177.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5177.webp',
  },
  {
    id: 'bunz-img-5187-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5187.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5187.webp',
  },
  {
    id: 'bunz-img-5202-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5202.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5202.webp',
  },
  {
    id: 'bunz-img-5207-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5207.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5207.webp',
  },
  {
    id: 'bunz-img-5208-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5208.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5208.webp',
  },
  {
    id: 'bunz-img-5217-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5217.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5217.webp',
  },
  {
    id: 'bunz-img-5219-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5219.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5219.webp',
  },
  {
    id: 'bunz-img-5220-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5220.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5220.webp',
  },
  {
    id: 'bunz-img-5223-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5223.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5223.webp',
  },
  {
    id: 'bunz-img-5253-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5253.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5253.webp',
  },
  {
    id: 'bunz-img-5254-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5254.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5254.webp',
  },
  {
    id: 'bunz-img-5262-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5262.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5262.webp',
  },
  {
    id: 'bunz-img-5269-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5269.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5269.webp',
  },
  {
    id: 'bunz-img-5272-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5272.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5272.webp',
  },
  {
    id: 'bunz-img-5280-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5280.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5280.webp',
  },
  {
    id: 'bunz-img-5287-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5287.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5287.webp',
  },
  {
    id: 'bunz-img-5293-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5293.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5293.webp',
  },
  {
    id: 'bunz-img-5318-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5318.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5318.webp',
  },
  {
    id: 'bunz-img-5323-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5323.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5323.webp',
  },
  {
    id: 'bunz-img-5391-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5391.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5391.webp',
  },
  {
    id: 'bunz-img-5400-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5400.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5400.webp',
  },
  {
    id: 'bunz-img-5401-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5401.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5401.webp',
  },
  {
    id: 'bunz-img-5454-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5454.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5454.webp',
  },
  {
    id: 'bunz-img-5456-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5456.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5456.webp',
  },
  {
    id: 'bunz-img-5459-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5459.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5459.webp',
  },
  {
    id: 'bunz-img-5468-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5468.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5468.webp',
  },
  {
    id: 'bunz-img-5469-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5469.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5469.webp',
  },
  {
    id: 'bunz-img-5481-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5481.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5481.webp',
  },
  {
    id: 'bunz-img-5489-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5489.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5489.webp',
  },
  {
    id: 'bunz-img-5492-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5492.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5492.webp',
  },
  {
    id: 'bunz-img-5512-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5512.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5512.webp',
  },
  {
    id: 'bunz-img-5570-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5570.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5570.webp',
  },
  {
    id: 'bunz-img-5581-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5581.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5581.webp',
  },
  {
    id: 'bunz-img-5665-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5665.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5665.webp',
  },
  {
    id: 'bunz-img-5666-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5666.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5666.webp',
  },
  {
    id: 'bunz-img-5668-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5668.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5668.webp',
  },
  {
    id: 'bunz-img-5670-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5670.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5670.webp',
  },
  {
    id: 'bunz-img-5745-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5745.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5745.webp',
  },
  {
    id: 'bunz-img-5747-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5747.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5747.webp',
  },
  {
    id: 'bunz-img-5748-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5748.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5748.webp',
  },
  {
    id: 'bunz-img-5752-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5752.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5752.webp',
  },
  {
    id: 'bunz-img-5770-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5770.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5770.webp',
  },
  {
    id: 'bunz-img-5789-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5789.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5789.webp',
  },
  {
    id: 'bunz-img-5835-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5835.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5835.webp',
  },
  {
    id: 'bunz-img-5860-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5860.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5860.webp',
  },
  {
    id: 'bunz-img-5894-2-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5894 2.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5894 2.webp',
  },
  {
    id: 'bunz-img-5894-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5894.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5894.webp',
  },
  {
    id: 'bunz-img-5895-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5895.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5895.webp',
  },
  {
    id: 'bunz-img-5900-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5900.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5900.webp',
  },
  {
    id: 'bunz-img-5935-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5935.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5935.webp',
  },
  {
    id: 'bunz-img-5979-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5979.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5979.webp',
  },
  {
    id: 'bunz-img-5980-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_5980.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5980.webp',
  },
  {
    id: 'bunz-img-5991-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_5991.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_5991.mp4',
  },
  {
    id: 'bunz-img-6017-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6017.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6017.webp',
  },
  {
    id: 'bunz-img-6028-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6028.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6028.webp',
  },
  {
    id: 'bunz-img-6031-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6031.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6031.webp',
  },
  {
    id: 'bunz-img-6043-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6043.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6043.webp',
  },
  {
    id: 'bunz-img-6046-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6046.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6046.webp',
  },
  {
    id: 'bunz-img-6099-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6099.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6099.webp',
  },
  {
    id: 'bunz-img-6122-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6122.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6122.webp',
  },
  {
    id: 'bunz-img-6123-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6123.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6123.webp',
  },
  {
    id: 'bunz-img-6139-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6139.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6139.webp',
  },
  {
    id: 'bunz-img-6166-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6166.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6166.webp',
  },
  {
    id: 'bunz-img-6167-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6167.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6167.webp',
  },
  {
    id: 'bunz-img-6212-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_6212.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6212.mp4',
  },
  {
    id: 'bunz-img-6252-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6252.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6252.webp',
  },
  {
    id: 'bunz-img-6254-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6254.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6254.webp',
  },
  {
    id: 'bunz-img-6256-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6256.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6256.webp',
  },
  {
    id: 'bunz-img-6264-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6264.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6264.webp',
  },
  {
    id: 'bunz-img-6277-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6277.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6277.webp',
  },
  {
    id: 'bunz-img-6294-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6294.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6294.webp',
  },
  {
    id: 'bunz-img-6315-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6315.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6315.webp',
  },
  {
    id: 'bunz-img-6335-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6335.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6335.webp',
  },
  {
    id: 'bunz-img-6338-2-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6338 2.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6338 2.webp',
  },
  {
    id: 'bunz-img-6338-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6338.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6338.webp',
  },
  {
    id: 'bunz-img-6347-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6347.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6347.webp',
  },
  {
    id: 'bunz-img-6356-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6356.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6356.webp',
  },
  {
    id: 'bunz-img-6368-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6368.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6368.webp',
  },
  {
    id: 'bunz-img-6372-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6372.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6372.webp',
  },
  {
    id: 'bunz-img-6393-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6393.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6393.webp',
  },
  {
    id: 'bunz-img-6394-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6394.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6394.webp',
  },
  {
    id: 'bunz-img-6420-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6420.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6420.webp',
  },
  {
    id: 'bunz-img-6486-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_6486.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6486.mp4',
  },
  {
    id: 'bunz-img-6519-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6519.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6519.webp',
  },
  {
    id: 'bunz-img-6538-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6538.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6538.webp',
  },
  {
    id: 'bunz-img-6672-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6672.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6672.webp',
  },
  {
    id: 'bunz-img-6703-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6703.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6703.webp',
  },
  {
    id: 'bunz-img-6707-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6707.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6707.webp',
  },
  {
    id: 'bunz-img-6725-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6725.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6725.webp',
  },
  {
    id: 'bunz-img-6733-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6733.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6733.webp',
  },
  {
    id: 'bunz-img-6792-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6792.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6792.webp',
  },
  {
    id: 'bunz-img-6811-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6811.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6811.webp',
  },
  {
    id: 'bunz-img-6854-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6854.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6854.webp',
  },
  {
    id: 'bunz-img-6908-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6908.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6908.webp',
  },
  {
    id: 'bunz-img-6996-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_6996.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_6996.webp',
  },
  {
    id: 'bunz-img-7042-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7042.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7042.webp',
  },
  {
    id: 'bunz-img-7111-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7111.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7111.webp',
  },
  {
    id: 'bunz-img-7135-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7135.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7135.webp',
  },
  {
    id: 'bunz-img-7156-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7156.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7156.webp',
  },
  {
    id: 'bunz-img-7189-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7189.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7189.webp',
  },
  {
    id: 'bunz-img-7193-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7193.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7193.webp',
  },
  {
    id: 'bunz-img-7219-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7219.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7219.webp',
  },
  {
    id: 'bunz-img-7236-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7236.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7236.webp',
  },
  {
    id: 'bunz-img-7237-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7237.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7237.webp',
  },
  {
    id: 'bunz-img-7249-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7249.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7249.webp',
  },
  {
    id: 'bunz-img-7271-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7271.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7271.webp',
  },
  {
    id: 'bunz-img-7272-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7272.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7272.webp',
  },
  {
    id: 'bunz-img-7289-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7289.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7289.webp',
  },
  {
    id: 'bunz-img-7351-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7351.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7351.webp',
  },
  {
    id: 'bunz-img-7352-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7352.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7352.webp',
  },
  {
    id: 'bunz-img-7386-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7386.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7386.webp',
  },
  {
    id: 'bunz-img-7392-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7392.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7392.webp',
  },
  {
    id: 'bunz-img-7397-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7397.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7397.webp',
  },
  {
    id: 'bunz-img-7398-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7398.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7398.webp',
  },
  {
    id: 'bunz-img-7415-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7415.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7415.webp',
  },
  {
    id: 'bunz-img-7416-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7416.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7416.webp',
  },
  {
    id: 'bunz-img-7421-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7421.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7421.webp',
  },
  {
    id: 'bunz-img-7440-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7440.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7440.webp',
  },
  {
    id: 'bunz-img-7474-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7474.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7474.webp',
  },
  {
    id: 'bunz-img-7482-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7482.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7482.webp',
  },
  {
    id: 'bunz-img-7511-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7511.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7511.webp',
  },
  {
    id: 'bunz-img-7532-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7532.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7532.webp',
  },
  {
    id: 'bunz-img-7541-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7541.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7541.webp',
  },
  {
    id: 'bunz-img-7612-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_7612.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7612.mp4',
  },
  {
    id: 'bunz-img-7626-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7626.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7626.webp',
  },
  {
    id: 'bunz-img-7630-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7630.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7630.webp',
  },
  {
    id: 'bunz-img-7642-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7642.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7642.webp',
  },
  {
    id: 'bunz-img-7654-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7654.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7654.webp',
  },
  {
    id: 'bunz-img-7684-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7684.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7684.webp',
  },
  {
    id: 'bunz-img-7744-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7744.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7744.webp',
  },
  {
    id: 'bunz-img-7797-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7797.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7797.webp',
  },
  {
    id: 'bunz-img-7841-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7841.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7841.webp',
  },
  {
    id: 'bunz-img-7845-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7845.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7845.webp',
  },
  {
    id: 'bunz-img-7846-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7846.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7846.webp',
  },
  {
    id: 'bunz-img-7852-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7852.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7852.webp',
  },
  {
    id: 'bunz-img-7854-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7854.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7854.webp',
  },
  {
    id: 'bunz-img-7903-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7903.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7903.webp',
  },
  {
    id: 'bunz-img-7926-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7926.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7926.webp',
  },
  {
    id: 'bunz-img-7941-2-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7941 2.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7941 2.webp',
  },
  {
    id: 'bunz-img-7941-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7941.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7941.webp',
  },
  {
    id: 'bunz-img-7960-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_7960.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_7960.webp',
  },
  {
    id: 'bunz-img-8016-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8016.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8016.webp',
  },
  {
    id: 'bunz-img-8020-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8020.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8020.webp',
  },
  {
    id: 'bunz-img-8023-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8023.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8023.webp',
  },
  {
    id: 'bunz-img-8037-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8037.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8037.webp',
  },
  {
    id: 'bunz-img-8114-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8114.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8114.webp',
  },
  {
    id: 'bunz-img-8142-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8142.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8142.webp',
  },
  {
    id: 'bunz-img-8178-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8178.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8178.webp',
  },
  {
    id: 'bunz-img-8245-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8245.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8245.webp',
  },
  {
    id: 'bunz-img-8246-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8246.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8246.webp',
  },
  {
    id: 'bunz-img-8290-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8290.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8290.webp',
  },
  {
    id: 'bunz-img-8313-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8313.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8313.webp',
  },
  {
    id: 'bunz-img-8338-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8338.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8338.webp',
  },
  {
    id: 'bunz-img-8345-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8345.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8345.webp',
  },
  {
    id: 'bunz-img-8354-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8354.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8354.webp',
  },
  {
    id: 'bunz-img-8356-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8356.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8356.webp',
  },
  {
    id: 'bunz-img-8365-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8365.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8365.webp',
  },
  {
    id: 'bunz-img-8397-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8397.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8397.webp',
  },
  {
    id: 'bunz-img-8431-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8431.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8431.webp',
  },
  {
    id: 'bunz-img-8508-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8508.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8508.webp',
  },
  {
    id: 'bunz-img-8544-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8544.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8544.webp',
  },
  {
    id: 'bunz-img-8551-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8551.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8551.webp',
  },
  {
    id: 'bunz-img-8625-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8625.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8625.webp',
  },
  {
    id: 'bunz-img-8657-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8657.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8657.webp',
  },
  {
    id: 'bunz-img-8663-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8663.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8663.webp',
  },
  {
    id: 'bunz-img-8683-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8683.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8683.webp',
  },
  {
    id: 'bunz-img-8725-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8725.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8725.webp',
  },
  {
    id: 'bunz-img-8727-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8727.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8727.webp',
  },
  {
    id: 'bunz-img-8731-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8731.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8731.webp',
  },
  {
    id: 'bunz-img-8754-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8754.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8754.webp',
  },
  {
    id: 'bunz-img-8796-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_8796.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8796.mp4',
  },
  {
    id: 'bunz-img-8807-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8807.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8807.webp',
  },
  {
    id: 'bunz-img-8813-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8813.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8813.webp',
  },
  {
    id: 'bunz-img-8852-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8852.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8852.webp',
  },
  {
    id: 'bunz-img-8921-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8921.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8921.webp',
  },
  {
    id: 'bunz-img-8974-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_8974.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_8974.webp',
  },
  {
    id: 'bunz-img-9017-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9017.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9017.webp',
  },
  {
    id: 'bunz-img-9107-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9107.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9107.webp',
  },
  {
    id: 'bunz-img-9138-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_9138.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9138.mp4',
  },
  {
    id: 'bunz-img-9147-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9147.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9147.webp',
  },
  {
    id: 'bunz-img-9189-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9189.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9189.webp',
  },
  {
    id: 'bunz-img-9197-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9197.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9197.webp',
  },
  {
    id: 'bunz-img-9198-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9198.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9198.webp',
  },
  {
    id: 'bunz-img-9201-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9201.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9201.webp',
  },
  {
    id: 'bunz-img-9220-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9220.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9220.webp',
  },
  {
    id: 'bunz-img-9229-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9229.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9229.webp',
  },
  {
    id: 'bunz-img-9232-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9232.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9232.webp',
  },
  {
    id: 'bunz-img-9275-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9275.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9275.webp',
  },
  {
    id: 'bunz-img-9359-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9359.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9359.webp',
  },
  {
    id: 'bunz-img-9434-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9434.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9434.webp',
  },
  {
    id: 'bunz-img-9442-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9442.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9442.webp',
  },
  {
    id: 'bunz-img-9469-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9469.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9469.webp',
  },
  {
    id: 'bunz-img-9493-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9493.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9493.webp',
  },
  {
    id: 'bunz-img-9565-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9565.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9565.webp',
  },
  {
    id: 'bunz-img-9589-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9589.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9589.webp',
  },
  {
    id: 'bunz-img-9593-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9593.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9593.webp',
  },
  {
    id: 'bunz-img-9597-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9597.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9597.webp',
  },
  {
    id: 'bunz-img-9605-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9605.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9605.webp',
  },
  {
    id: 'bunz-img-9610-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9610.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9610.webp',
  },
  {
    id: 'bunz-img-9612-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9612.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9612.webp',
  },
  {
    id: 'bunz-img-9621-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9621.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9621.webp',
  },
  {
    id: 'bunz-img-9622-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9622.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9622.webp',
  },
  {
    id: 'bunz-img-9784-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9784.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9784.webp',
  },
  {
    id: 'bunz-img-9788-mp4',
    type: 'video' as const,
    src: '/media/images/bunz/IMG_9788.mp4',
    poster: '',
    hasAudio: false,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9788.mp4',
  },
  {
    id: 'bunz-img-9856-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9856.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9856.webp',
  },
  {
    id: 'bunz-img-9885-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9885.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9885.webp',
  },
  {
    id: 'bunz-img-9916-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9916.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9916.webp',
  },
  {
    id: 'bunz-img-9943-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/IMG_9943.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: IMG_9943.webp',
  },
  {
    id: 'bunz-screenshot-2023-07-24-at-5-25-03-pm-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/Screenshot 2023-07-24 at 5.25.03 PM.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: Screenshot 2023-07-24 at 5.25.03 PM.webp',
  },
  {
    id: 'bunz-screenshot-2025-11-20-at-11-03-19-pm-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/Screenshot 2025-11-20 at 11.03.19 PM.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: Screenshot 2025-11-20 at 11.03.19 PM.webp',
  },
  {
    id: 'bunz--com-apple-pasteboard-hcn247-webp',
    type: 'photo' as const,
    src: '/media/images/bunz/_com.apple.Pasteboard.hcN247.webp',
    width: 1024,
    height: 1024,
    caption: 'Bunz 🐱',
    alt: 'Bunz: _com.apple.Pasteboard.hcN247.webp',
  }
];
